service: employees
frameworkVersion: '2 || 3'

custom:
  tableName: 'Employees'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ EmployeeTable, Arn ]
  environment:
    TABLENAME: ${self:custom.tableName}
    NODE_ENV: 'production'
    REGION: 'ap-south-1'
    COGNITO_USER_POOL_ID: 'ap-south-1_Pj5phYg8U'
functions:
  api:
    handler: index.handler
    layers:
      - arn:aws:lambda:ap-south-1:890756660068:layer:DynamoDB-Express-SDK:1
    events:
      - httpApi: '*'

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: LocationID
            AttributeType: S
          - AttributeName: EmpCode
            AttributeType: S
        KeySchema:
          - AttributeName: LocationID
            KeyType: HASH
          - AttributeName: EmpCode
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
